import QCProvider from "./QCProvider";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QCProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </QCProvider>
  );
}
